"""Annotated config emission and reuse (spec §8.6, D27).

Every inferred value is written with *how* it was determined and *how
confident* the tool is. Discovery is a bootstrap, not a black box: a user who
sees `confidence: low` next to an extraction path can correct it by hand and
re-run, and that is the intended workflow rather than a failure path.

Keyed by URL hash, not by working directory. Two targets in one directory would
otherwise collide, and a shared gateway URL routing to different backends would
reuse the wrong config.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

from sweepeval.schema.hashing import hash_obj, sha256_hex

__all__ = [
    "EmittedConfig",
    "config_dir_for",
    "emit_config",
    "load_config",
    "was_hand_edited",
]

_GENERATED_MARKER = "generated_content_hash"


def config_dir_for(root: Path, url: str, fingerprint: str | None = None) -> Path:
    """``.sweepeval/discovery/<url_hash>/`` (§8.6)."""
    digest = fingerprint or sha256_hex(url.encode())
    return Path(root) / "discovery" / digest[:16]


@dataclass
class EmittedConfig:
    path: Path
    payload: dict[str, Any]
    copied_to: Path | None = None


def _content_hash(payload: dict[str, Any]) -> str:
    body = {k: v for k, v in payload.items() if k != _GENERATED_MARKER}
    return hash_obj(body)[:16]


def emit_config(
    root: Path,
    url: str,
    payload: dict[str, Any],
    *,
    fingerprint: str | None = None,
    also_copy_to: Path | None = None,
    force: bool = False,
) -> EmittedConfig:
    """Write the annotated config, refusing to clobber hand edits."""
    directory = config_dir_for(root, url, fingerprint)
    directory.mkdir(parents=True, exist_ok=True)
    target = directory / "sweepeval.yaml"

    if target.exists() and not force and was_hand_edited(target):
        raise FileExistsError(
            f"refusing to overwrite hand-edited {target}\n"
            "  its content hash differs from the last generated one\n"
            "  --force to overwrite, or -o FILE to write elsewhere"
        )

    stamped = dict(payload)
    stamped[_GENERATED_MARKER] = _content_hash(payload)
    text = _render(stamped)
    target.write_text(text, encoding="utf-8")

    copied: Path | None = None
    if also_copy_to is not None:
        destination = Path(also_copy_to)
        if not destination.exists() or force or not was_hand_edited(destination):
            destination.write_text(text, encoding="utf-8")
            copied = destination

    return EmittedConfig(path=target, payload=stamped, copied_to=copied)


def was_hand_edited(path: Path) -> bool:
    """True when the file's content no longer matches its generated stamp.

    A config with no stamp at all is treated as hand-written, which is the
    conservative reading: it was not produced by this tool.
    """
    try:
        payload = yaml.safe_load(Path(path).read_text(encoding="utf-8"))
    except (OSError, yaml.YAMLError):
        return True
    if not isinstance(payload, dict):
        return True
    stamp = payload.get(_GENERATED_MARKER)
    if not stamp:
        return True
    return str(stamp) != _content_hash(payload)


def load_config(path: Path) -> dict[str, Any]:
    payload = yaml.safe_load(Path(path).read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"{path} is not a mapping")
    return payload


_HEADER = """\
# Generated by sweepeval discovery. Every inferred value carries how it was
# determined and how confident the tool is.
#
# This file is meant to be edited. Correct anything marked low confidence and
# re-run; discovery will not overwrite your edits without --force.
"""


def _render(payload: dict[str, Any]) -> str:
    return _HEADER + yaml.safe_dump(payload, sort_keys=False, allow_unicode=True)
